import assert from 'node:assert/strict';
import test from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { readFile } from 'node:fs/promises';
import { enqueueAppointmentReminder, runAppointmentAutomation, createNewCustomerNotification, createDailyBriefing } from '../src/lib/crm-automation.js';
import { createCrmSensDeliveryAdapter } from '../src/lib/crm-sens.js';
const migration = await readFile(new URL('../migrations/0048_crm_automation.sql', import.meta.url), 'utf8');
function db() { const sqlite = new DatabaseSync(':memory:'); sqlite.exec(`CREATE TABLE CrmTenants(id TEXT PRIMARY KEY,name TEXT,brand TEXT,logo_url TEXT,suspended INTEGER DEFAULT 0,created_at TEXT); CREATE TABLE CrmUsers(id TEXT PRIMARY KEY,tenant_id TEXT,email TEXT,role TEXT,active INTEGER DEFAULT 1,created_at TEXT); CREATE TABLE Estimates(id TEXT PRIMARY KEY,CrmTenantId TEXT,Name TEXT,Phone TEXT,Email TEXT,Address TEXT,EstimateAmount INTEGER,SubmittedAt TEXT,Source TEXT,Platform TEXT); CREATE TABLE CrmAppointments(id TEXT PRIMARY KEY,tenant_id TEXT,estimate_id TEXT,kind TEXT,starts_at TEXT,location TEXT,address TEXT,status TEXT DEFAULT 'scheduled',CrmVersion INTEGER DEFAULT 1,created_by TEXT,created_at TEXT); CREATE TABLE CrmNotificationTemplates(tenant_id TEXT,kind TEXT,state TEXT,body TEXT,enabled INTEGER,updated_by TEXT,updated_at TEXT,PRIMARY KEY(tenant_id,kind,state)); CREATE TABLE CrmNotificationOutbox(id TEXT PRIMARY KEY,tenant_id TEXT,appointment_id TEXT,appointment_version INTEGER,notification_type TEXT,recipient_id TEXT,channel TEXT,idempotency_key TEXT UNIQUE,due_at TEXT,status TEXT,payload_json TEXT,reserved_at TEXT,sent_at TEXT,created_at TEXT,cancelled_at TEXT); CREATE TABLE CrmNotifications(id TEXT PRIMARY KEY,tenant_id TEXT,type TEXT,actor_id TEXT,payload_json TEXT,created_at TEXT); CREATE TABLE CrmNotificationRecipients(notification_id TEXT,tenant_id TEXT,recipient_id TEXT,created_at TEXT,read_at TEXT,PRIMARY KEY(notification_id,recipient_id)); CREATE TABLE CrmDailyBriefings(id TEXT PRIMARY KEY,tenant_id TEXT,recipient_id TEXT,briefing_date TEXT,notification_id TEXT,created_at TEXT,UNIQUE(tenant_id,recipient_id,briefing_date)); CREATE TABLE CrmAuditLogs(id INTEGER PRIMARY KEY,tenant_id TEXT,actor_id TEXT,estimate_id TEXT,action TEXT,created_at TEXT);`); sqlite.exec(migration); return { exec: (sql) => sqlite.exec(sql), batch: async (statements) => { for (const statement of statements) await statement.run(); }, prepare(sql) { const statement = sqlite.prepare(sql); return { get: (...args) => statement.get(...args), all: (...args) => statement.all(...args), run: (...args) => { const result = statement.run(...args); return { changes: result.changes, lastInsertRowid: result.lastInsertRowid }; }, bind(...args) { return { first: async () => statement.get(...args), all: async () => ({ results: statement.all(...args) }), run: async () => { const result = statement.run(...args); return { meta: { changes: result.changes, last_row_id: result.lastInsertRowid } }; } }; } }; } }; }
function seed(d) { d.exec("INSERT INTO CrmTenants VALUES ('t1','Dayone','day1design','logo',0,'2026-09-09T00:00:00Z'),('t2','Other','other','',0,'2026-09-09T00:00:00Z'); INSERT INTO CrmUsers VALUES ('o1','t1','o@example.test','owner',1,'2026-09-09T00:00:00Z'),('s1','t1','s@example.test','staff',1,'2026-09-09T00:00:00Z'),('o2','t2','x@example.test','owner',1,'2026-09-09T00:00:00Z'); INSERT INTO Estimates(id,CrmTenantId,Name,SubmittedAt,Source,Platform) VALUES ('e1','t1','고객','2026-09-09T00:00:00Z','homepage',''); INSERT INTO CrmNotificationTemplates VALUES ('t1','visit','approved','visit {{name}}',1,'o1','2026-09-09T00:00:00Z'),('t1','measurement','approved','measurement {{name}}',1,'o1','2026-09-09T00:00:00Z');"); }
test('migration creates version-keyed reminder and invalidates reschedule/cancel/suspend/template off', async () => { const d = db(); seed(d); d.exec("INSERT INTO CrmAppointments VALUES ('a1','t1','e1','visit','2026-09-10T06:00:00.000Z','office','addr','scheduled',1,'o1','2026-09-09T00:00:00Z');"); let row = d.prepare("SELECT * FROM CrmNotificationOutbox WHERE appointment_id='a1'").get(); assert.equal(row.appointment_version, 1); assert.equal(row.idempotency_key, 't1:a1:1:visit_reminder:customer:customer'); d.exec("UPDATE CrmAppointments SET CrmVersion=2,starts_at='2026-09-10T08:00:00.000Z' WHERE id='a1'"); assert.equal(d.prepare("SELECT status FROM CrmNotificationOutbox WHERE appointment_version=1").get().status, 'cancelled'); assert.equal(d.prepare("SELECT COUNT(*) n FROM CrmNotificationOutbox WHERE appointment_id='a1' AND status='queued'").get().n, 1); d.exec("UPDATE CrmAppointments SET status='cancelled',CrmVersion=3 WHERE id='a1'"); assert.equal(d.prepare("SELECT COUNT(*) n FROM CrmNotificationOutbox WHERE appointment_id='a1' AND status='queued'").get().n, 0); d.exec("UPDATE CrmAppointments SET status='scheduled',CrmVersion=4 WHERE id='a1'; UPDATE CrmTenants SET suspended=1 WHERE id='t1'"); assert.equal(d.prepare("SELECT COUNT(*) n FROM CrmNotificationOutbox WHERE tenant_id='t1' AND status='queued'").get().n, 0); d.exec("UPDATE CrmTenants SET suspended=0 WHERE id='t1'; UPDATE CrmAppointments SET CrmVersion=5 WHERE id='a1'; UPDATE CrmNotificationTemplates SET enabled=0 WHERE tenant_id='t1' AND kind='visit'"); assert.equal(d.prepare("SELECT COUNT(*) n FROM CrmNotificationOutbox WHERE tenant_id='t1' AND status='queued'").get().n, 0); });
test('missing adapter blocks due work and never marks sent; duplicate tick is idempotent', async () => { const d = db(); seed(d); d.exec("INSERT INTO CrmAppointments VALUES ('a1','t1','e1','visit','2026-09-10T06:00:00.000Z','office','addr','scheduled',1,'o1','2026-09-09T00:00:00Z');"); const first = await runAppointmentAutomation(d, { tenantId: 't1', now: '2026-09-10T03:00:00.000Z' }); assert.equal(first.results[0].status, 'blocked'); const row = d.prepare("SELECT status,delivery_status,blocked_reason FROM CrmNotificationOutbox WHERE appointment_id='a1'").get(); assert.equal(row.status, 'queued'); assert.equal(row.delivery_status, 'blocked'); assert.equal(row.blocked_reason, 'delivery_adapter_missing'); const second = await runAppointmentAutomation(d, { tenantId: 't1', now: '2026-09-10T03:01:00.000Z' }); assert.equal(second.results[0].status, 'blocked'); assert.equal(d.prepare("SELECT sent_at FROM CrmNotificationOutbox WHERE appointment_id='a1'").get().sent_at, null); });
test('delivery rechecks and sends once only after explicit adapter acceptance', async () => { const d = db(); seed(d); d.exec("INSERT INTO CrmAppointments VALUES ('a1','t1','e1','measurement','2026-09-10T06:00:00.000Z','site','addr','scheduled',1,'o1','2026-09-09T00:00:00Z');"); const sent = await runAppointmentAutomation(d, { tenantId: 't1', now: '2026-09-10T03:00:00.000Z', deliveryAdapter: { send: async () => ({ accepted: true }) } }); assert.equal(sent.results[0].status, 'sent'); assert.equal(d.prepare("SELECT status,delivery_status FROM CrmNotificationOutbox WHERE appointment_id='a1'").get().status, 'sent'); assert.equal((await runAppointmentAutomation(d, { tenantId: 't1', now: '2026-09-10T04:00:00.000Z', deliveryAdapter: { send: async () => ({ accepted: true }) } })).processed, 0); });
test('delivery adapter receives current appointment time and renders it in KST', async () => {
  const d = db(); seed(d);
  d.exec("UPDATE Estimates SET Phone='010-1234-5678' WHERE id='e1'; UPDATE CrmNotificationTemplates SET body='visit {{name}} {{date}} {{time}} {{location}}' WHERE tenant_id='t1' AND kind='visit'; INSERT INTO CrmAppointments VALUES ('a1','t1','e1','visit','2026-09-10T06:30:00.000Z','강남본점','서울시 강남구','scheduled',1,'o1','2026-09-09T00:00:00Z');");
  const requests = [];
  const adapter = createCrmSensDeliveryAdapter({ CRM_SENS_TENANTS_JSON: JSON.stringify({ t1: { from: '0212345678', serviceId: 'tenant-service', contactPhone: '02-1234-5678' } }) }, {
    send: async (requestEnv, request) => {
      requests.push({ requestEnv, request });
      return { ok: true, status: 202, body: JSON.stringify({ requestId: 'request-1', statusCode: '202', statusName: 'success' }) };
    },
  });
  const result = await runAppointmentAutomation(d, { tenantId: 't1', now: '2026-09-10T03:30:00.000Z', deliveryAdapter: adapter });
  assert.equal(result.results[0].status, 'sent');
  assert.equal(requests.length, 1);
  assert.equal(requests[0].request.to, '010-1234-5678');
  assert.match(requests[0].request.content, /2026-09-10 15:30/);
  assert.match(requests[0].request.content, /강남본점/);
});
test('new customer notification is source-grounded and idempotent per estimate', async () => { const d = db(); seed(d); const result = await createNewCustomerNotification(d, { tenantId: 't1', actorId: 'o1', estimateId: 'e1' }); assert.equal(result.created, false); assert.equal(result.reason, 'already_created'); assert.equal(d.prepare("SELECT COUNT(*) n FROM CrmNotificationRecipients WHERE tenant_id='t2'").get().n, 0); const row = d.prepare("SELECT type,event_key,payload_json FROM CrmNotifications WHERE event_key='new_customer:t1:e1'").get(); assert.equal(row.type, 'new_customer'); assert.match(row.payload_json, /estimate_id/); });
test('short-notice appointment is permanently manual-review blocked', async () => { const d = db(); seed(d); const row = await enqueueAppointmentReminder(d, { tenantId: 't1', appointmentId: 'a-short', version: 1, kind: 'visit', startsAt: '2026-09-10T04:00:00.000Z', createdAt: '2026-09-10T02:00:00.000Z' }); assert.equal(row.delivery_status, 'blocked'); assert.equal(row.blocked_reason, 'short_notice_manual_review'); });
test('daily briefing rejects execution before 10:00 KST', async () => { const d = db(); seed(d); await assert.rejects(() => createDailyBriefing(d, { tenantId: 't1', recipientId: 'o1', date: '2026-09-10', now: '2026-09-10T00:59:59.000Z' }), /briefing_not_due/); });
