import test from 'node:test';import assert from 'node:assert/strict';import {readMobileBriefing} from '../src/lib/crm-briefing-reader.js';
const req=new Request('https://test/api/mobile/briefings/latest');
const owner={role:'owner',tenant_id:'day1design'};
function env(row,seen,snapshot){return {DB:{prepare:(query)=>({bind(...args){seen?.push({query,args});return this},first:async()=>row})},CRM_CACHE:{get:async key=>key==='report'?{size:8,text:async()=>'analysis'}:key==='snapshot'?{size:Buffer.byteLength(JSON.stringify(snapshot||{})),text:async()=>JSON.stringify(snapshot||{})}:{size:3,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}}};}
test('staff and other tenant cannot read Day1 report',async()=>{assert.equal((await readMobileBriefing(req,env({}),{...owner,role:'staff'},'/briefings/latest')).status,403);assert.equal((await (await readMobileBriefing(req,{}, {...owner,tenant_id:'other'},'/briefings/latest')).json()).available,false)});
test('latest combines stored analysis and protected image path',async()=>{const r=await (await readMobileBriefing(req,env({id:'daily-1',EndDate:'2026-09-08',RequestedAt:'2026-09-09T01:00:00Z',ReportKey:'report',ImageKey:'image',Status:'success'}),owner,'/briefings/latest')).json();assert.equal(r.analysis,'analysis');assert.equal(r.report_date,'2026-09-08');assert.equal(r.published_at,'2026-09-09T01:00:00Z');assert.equal(r.image_path,'/api/mobile/briefings/daily-1/image');});
test('latest exposes bounded snapshot visualization without customer fields',async()=>{const snapshot={reportDate:'2026-09-08',day:{ok:true,range:{startDate:'2026-09-08',endDate:'2026-09-08'},ads:{summary:{impressions:100,clicks:10,spend:20,leads:2,ctr:.1,cpc:2,cpm:200,cpl:10},efficiency:{previous:{startDate:'2026-09-07',endDate:'2026-09-07'},prevTotals:{impressions:50,clicks:5,spend:10,leads:1,ctr:.1,cpc:2,cpm:200,cpl:10}}},leads:{daily:[{day:'2026-09-08',n:3}],bySource:[{source:'meta',n:3}]},traffic:{summary:{sessions:12}}}};const r=await(await readMobileBriefing(req,env({id:'daily-1',EndDate:'2026-09-08',RequestedAt:'2026-09-09T01:00:00Z',SnapshotKey:'snapshot',Status:'success'},undefined,snapshot),owner,'/briefings/latest')).json();assert.equal(r.visualization.metrics.length,8);assert.equal(r.visualization.metrics[0].value,20);assert.equal(r.visualization.metrics[0].previous,10);assert.deepEqual(r.visualization.channels,[{label:'meta',value:3,unit:'건'}]);assert.equal(r.visualization.actions.length,0);assert.equal(r.visualization.period.start,'2026-09-08');assert.equal(r.visualization.comparison_period.start,'2026-09-07');assert.equal(JSON.stringify(r.visualization).includes('customer@example.com'),false);});
test('visualization exposes only source-grounded analyst action cards',async()=>{const snapshot={reportDate:'2026-09-08',day:{ok:true,range:{startDate:'2026-09-08',endDate:'2026-09-08'},ads:{summary:{impressions:100,clicks:10,spend:20,leads:2},efficiency:{previous:{startDate:'2026-09-07',endDate:'2026-09-07'},prevTotals:{impressions:50,clicks:5,spend:10,leads:1}}},leads:{daily:[{day:'2026-09-08',n:3}],bySource:[{source:'meta',n:3}]},traffic:{summary:{sessions:12}}},stats:{funnel:{bottleneck:{from:'클릭',at:'Meta 집계 리드',passThrough:.3},verdict:'클릭까지 따라왔지만 Meta 집계 리드는 30%만 받았다.'},leadReconciliation:{metaReportedLeads:4,storedLeadsFromMeta:3,gap:1,note:'Meta 집계가 저장된 Meta 접수보다 많다.'},leads:{total:3,smallSampleWarning:'접수 3건은 세분화해서 순위를 매리기에 부족하다.'}}};const r=await(await readMobileBriefing(req,env({id:'daily-1',EndDate:'2026-09-08',RequestedAt:'2026-09-09T01:00:00Z',SnapshotKey:'snapshot',Status:'success'},undefined,snapshot),owner,'/briefings/latest')).json();assert.deepEqual(r.visualization.actions.map((item)=>item.type),['funnel_bottleneck','lead_reconciliation','small_sample']);assert.match(r.visualization.actions[0].body,/분석 기준일 2026-09-08/);assert.equal(r.visualization.actions[0].evidence.pass_through,.3);assert.equal(r.visualization.actions[1].evidence.gap,1);assert.equal(JSON.stringify(r.visualization.actions).includes('@'),false);});
test('visualization derives CPM from same-period spend and impressions when summary CPM is absent',async()=>{const snapshot={reportDate:'2026-09-08',day:{ok:true,range:{startDate:'2026-09-08',endDate:'2026-09-08'},ads:{summary:{impressions:15930,clicks:10,spend:220.87,leads:2},efficiency:{previous:{startDate:'2026-09-07',endDate:'2026-09-07'},prevTotals:{impressions:50,clicks:5,spend:10,leads:1}}}}};const read=async(summary)=>{const current={...snapshot,day:{...snapshot.day,ads:{...snapshot.day.ads,summary}}};const r=await(await readMobileBriefing(req,env({id:'daily-1',EndDate:'2026-09-08',SnapshotKey:'snapshot',Status:'success'},undefined,current),owner,'/briefings/latest')).json();return r.visualization.metrics.find((item)=>item.key==='cpm').value;};assert.equal(await read(snapshot.day.ads.summary),13.865);for(const impressions of [0,null,-1])assert.equal(await read({...snapshot.day.ads.summary,impressions}),null);assert.equal(await read({...snapshot.day.ads.summary,spend:0}),0);});
test('latest period filters by analysis date and preserves tenant boundary',async()=>{const seen=[];const r=await(await readMobileBriefing(new Request('https://test/api/mobile/briefings/latest?start=2026-09-08&end=2026-09-08'),env({id:'daily-1',EndDate:'2026-09-08',RequestedAt:'2026-09-09T01:00:00Z',Status:'success'},seen),owner,'/briefings/latest')).json();assert.equal(r.report_date,'2026-09-08');assert.match(seen[0].query,/EndDate BETWEEN \? AND \?/);assert.deepEqual(seen[0].args,['2026-09-08','2026-09-08']);});
test('invalid or partial briefing period is rejected',async()=>{for(const url of ['?start=2026-09-08','?start=2026-09-10&end=2026-09-08','?start=2026-02-30&end=2026-03-01','?start=2025-01-01&end=2026-01-02'])assert.equal((await readMobileBriefing(new Request('https://test/api/mobile/briefings/latest'+url),env(null),owner,'/briefings/latest')).status,400);});
test('image reads bounded private object and rejects missing report',async()=>{let r=await(await readMobileBriefing(req,env({ImageKey:'image'}),owner,'/briefings/daily-1/image')).json();assert.equal(r.base64,'AQID');assert.equal((await readMobileBriefing(req,env(null),owner,'/briefings/daily-1/image')).status,404)});
